version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'mobile_labs_database'
    ports:
      - $MYSQL_LOCAL_PORT: 5001
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: react-native-app
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-data: